### ISSUE TITLE
squadra

### ISSUE THREAD

**Issue by sonoFranco** [AugustinSorel/gym-graphs#185]
Ciao, è possibile creare una squadra virtuale e vedere tutti i risultati dei singoli atleti? Grazie

**Comment by AugustinSorel** [comment]
Hi, right now no this isn't possible. But I really like that idea as it's quite fun. I will try to give this feature a shot and see if I can implement it. Thanks for the suggestion 😀

Ciao, in questo momento no, non è possibile. Ma mi piace davvero l'idea perché è piuttosto divertente. Proverò a provare questa funzionalità e vedrò se riesco a implementarla. Grazie per il suggerimento 😀

**Comment by sonoFranco** [comment]
Grazie , ciao

Il giorno mar 25 giu 2024 alle ore 16:02 Augustin ***@***.***>
ha scritto:

**Comment by AugustinSorel** [comment]
> Grazie , ciao Il giorno mar 25 giu 2024 alle ore 16:02 Augustin ***@***.***> ha scritto:

Hello, just to let you know that I have just merged into production this feature. You can now add teams and invite members into it. For now, this feature is very basic but I will add more features into it. Let me know if I am missing anything. 

Ciao, solo per farti sapere che ho appena messo in produzione questa funzionalità. Ora puoi aggiungere squadre e invitare membri. Per ora, questa funzionalità è molto semplice ma ne aggiungerò altre. Fammi sapere se mi manca qualcosa.

You can add a new team by clicking the arrow next to your name in the nav bar header
![image](https://github.com/AugustinSorel/gym-graphs/assets/48162609/dd6964f6-8096-4d35-9510-8910e51fd313)
